In [9]:
from fastai.tabular.all import *

# Télécharge et décompresse les données
path = untar_data(URLs.ADULT_SAMPLE)

# Charge les données tabulaires
dls = TabularDataLoaders.from_csv(
    path/'adult.csv',
    path=path,
    y_names='salary',
    cat_names=['workclass', 'education', 'marital-status', 'occupation', 'relationship'],
    cont_names=['age', 'fnlwgt', 'education-num'],
    procs=[Categorify, FillMissing, Normalize]
)

C:\Users\33781\AppData\Local\Programs\Python\Python310\lib\site-packages\fastai\tabular\core.py:314: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  to[n].fillna(self.na_dict[n], inplace=True)

In [8]:
#see the data
dls.show_batch()

In [13]:
learn = tabular_learner(dls, metrics=accuracy)
# Train the model using the 1-cycle policy for 2 epochs
learn.fit_one_cycle(2)
# - 2: Number of epochs (complete passes through the training dataset)